version: '3.9'

services:

  db:
    image: postgres:latest
    restart: "no"
    container_name: OtherDatabase
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "8102:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: mydatabase

networks:
  default:
    external: true
    name: my-net